feature dockerize & deployment plugin & attachment button
PlanQK/workflow-modeler pull request #69
Opened 2023-06-22 11:36 UTC by KuhnMn

This PR includes the extraction of the deployment functionality into its own plugin, an extended Dockerfile, as well as an initial button and window for attaching deployment artifacts to service tasks.

2023-07-04 10:58 UTC, LaviniaStiliadou commented
There are some issues regarding this PR:
- I get the following error message when clicking on the "Artifact Wizard" Button multiple times:
  `Warning: You are calling ReactDOMClient.createRoot() on a container that has already been passed to createRoot() before. Instead, call root.render() on the existing root instead if you want to update it.`

  Possible solution:
  - remove wizardDiv from the QuantumWorkflowModeler
  - create the wizardDiv inside ArtifactUpload and check if the wizardDiv exist before the createRoot. If yes -> remove, else create.

- Add a hover effect for the Artifact Wizard Button
- Change the layout for Artifact Wizard Button so it looks similar to the other buttons. For example the border is too thick, the current font size is 15px but we use 13px in the properties panel  
- Rename Artifact Wizard to Upload Artifact
- Rename OpenTosca to OpenTOSCA
- Rename Show deployment to Show Deployment
- Rename Hide deployment to Hide Deployment
- The icon for OpenTOSCA is misleading. I suggest using the following [icon](https://github.com/OpenTOSCA)
- The icons for the first subbuttons of the OpenTOSCA Plugin are identical. I suggest using the following icons: [show](https://www.onlinewebfonts.com/icon/231249), [hide](https://www.onlinewebfonts.com/icon/349222)
- Also, I am missing some docs. Regarding the new functionality show/hide deployment, the new icon ...

2023-07-13 09:31 UTC, LaviniaStiliadou commented
- Remove wizard also from the code (ArtifactWizardModal -> ArtifactWizard)
- QuantumWorkflowModeler: modal-container is not really a meaningful name, imagine having multiple modals
- separate the styling of the OpenTOSCA Button and the Service Deployment Icon, only the plugin should have the new icon as suggested in my previous comment
- screenshot is not up-to-date
- add a title to the upload artifact button to be consistent with the other buttons
- take a look at your code documentation, in the ArtifactWizardModal you have the comments of the ConfigModal

2023-07-13 13:53 UTC, wiomoc commented
> QuantumWorkflowModeler: modal-container is not really a meaningful name, imagine having multiple modals
Using the `createRoot` technic, they all can use the same container

2023-08-25 20:58 UTC, LaviniaStiliadou requested changes
Summary:

- Change the license year to 2023 
- Look again at the naming of OpenTOSCA 
- Add the option to update the service template when uploading a new file.

2023-08-25 20:58 UTC, LaviniaStiliadou commented on .vscode/settings.json
do we really need this?

2023-08-25 20:58 UTC, LaviniaStiliadou commented on components/bpmn-q/modeler-component/editor/plugin/PluginHandler.js
OpenTOSCA as mentioned in previous review

2023-08-25 20:58 UTC, LaviniaStiliadou commented on components/bpmn-q/modeler-component/extensions/opentosca/OpenTOSCAPlugin.js
Again OpenTOSCA

2023-08-25 20:58 UTC, LaviniaStiliadou commented on components/bpmn-q/modeler-component/extensions/opentosca/deployment/OpenTOSCAUtils.js
Update the license year in every file to 2023

2023-08-25 20:58 UTC, LaviniaStiliadou commented on components/bpmn-q/modeler-component/extensions/opentosca/deployment/WineryUtils.js
add a method to update the service template when uploading a new artifact (also mentioned in previous review)

2023-08-25 20:58 UTC, LaviniaStiliadou commented on components/bpmn-q/modeler-component/extensions/opentosca/framework-config/config-manager.js
license year

2023-08-25 20:58 UTC, LaviniaStiliadou commented on components/bpmn-q/modeler-component/extensions/opentosca/framework-config/config.js
license year

2023-08-25 20:58 UTC, LaviniaStiliadou commented on components/bpmn-q/modeler-component/extensions/opentosca/framework-config/index.js
again update the license year

2023-08-25 20:58 UTC, LaviniaStiliadou commented on components/bpmn-q/modeler-component/extensions/opentosca/modeling/index.js
license year

2023-08-25 20:58 UTC, LaviniaStiliadou commented on components/bpmn-q/modeler-component/extensions/opentosca/utilities/Utilities.js
license year

2023-08-25 20:58 UTC, LaviniaStiliadou commented on components/bpmn-q/test/tests/opentosca/opentosca-config.spec.js
Test **OpenTOSCA** ConfigManager, same for endpoint

2023-08-25 20:58 UTC, LaviniaStiliadou commented on doc/quantum-workflow-modeler/extensions/opentosca-plugin/OpenToscaUI.jpg
rename file to OpenTOSCAUI

2023-08-25 20:58 UTC, LaviniaStiliadou commented on .github/workflows/docker-publish.yaml
in our case its the planqk organization

2023-08-25 20:58 UTC, LaviniaStiliadou commented on Dockerfile
would be nice to include also the other variables (see webpack.config)

2023-08-25 20:58 UTC, LaviniaStiliadou commented on README.md
planqk organization

2023-08-25 20:58 UTC, LaviniaStiliadou commented on components/bpmn-q/modeler-component/editor/plugin/PluginHandler.js
again why do we need the !== 'false' check? If you really want to keep that then at least change the webpack.config otherwise your code does not work

2023-08-25 20:58 UTC, LaviniaStiliadou commented on components/bpmn-q/webpack.config.js
Do we really need all changes in that file? I doubt that we need to change the winery endpoint

2023-10-16 10:52 UTC, LaviniaStiliadou commented on Dockerfile
QHANA_GET_PLUGIN_URL is missing

2023-10-16 10:52 UTC, LaviniaStiliadou commented on components/bpmn-q/modeler-component/editor/ui/DeploymentButton.js
Handle the result of a close operation on the tramfpr,atopm? Fix this

2023-10-16 10:52 UTC, LaviniaStiliadou commented on components/bpmn-q/modeler-component/extensions/quantme/configTabs/QuantMETab.js
change BPMNConfigTab to QuantMETab

2023-10-22 22:04 UTC, LaviniaStiliadou reviewed
- Upload von WAR-Java17 and WAR-Java8 always say that the service template creation failed. The service template exists but looks wrong
- Update of service template is not working correctly when doing this: Upload first PythonArchiveArtifact then WAR --> two top node, same for WAR then PythonArchiveArtifact

2023-10-23 08:42 UTC, wederbn approved these changes

2023-10-23 08:42 UTC, merged