Fix missing scrollbar in xml viewer
PlanQK/workflow-modeler pull request #91
Opened 2023-09-18 13:15 UTC by LaviniaStiliadou

Should fix issue #79.

2023-09-27 09:44 UTC, mbeisel requested changes
At the bottom of the Workflow modeler there is a whitespace - when opening the XML-Viewer it is even larger than usual. Can the whitespace be removed altogether or at least remain the same when opening the XML viewer?
![grafik](https://github.com/PlanQK/workflow-modeler/assets/19931367/b8e49b50-b91a-452c-9cb8-4cd204ecefae)

2023-09-27 09:44 UTC, mbeisel commented on components/bpmn-q/modeler-component/QuantumWorkflowModeler.js
> +/* global ace */
shouldn't this be removed?

2023-10-04 09:46 UTC, LaviniaStiliadou commented on components/bpmn-q/modeler-component/QuantumWorkflowModeler.js
> +/* global ace */
Great point, I removed it

2023-10-24 15:29 UTC, wederbn approved these changes
LGTM

2023-10-24 15:31 UTC, merged